# O nome do seu projeto
name: 'lakehouse_models'
version: '1.0.0'

# O perfil do seu profiles.yml
profile: 'lakehouse_models'

# Caminhos dos arquivos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos
models:
  
  lakehouse_models: 
    
    # Configuração específica para a pasta 'silver'
    silver:
      +schema: "stock"  # Salva no dataset 'stock_silver'
      +materialized: "table"  # Salva como tabela
    
    